import { Segmented, Slider, Checkbox, Button, Divider, Tooltip } from "antd";
import { FlagOutlined, EditOutlined, InfoCircleOutlined } from "@ant-design/icons";

interface DatasetLayerControlPanelProps {
  // Basemap
  mapStyle: string;
  onMapStyleChange: (style: string) => void;
  // Data layers
  showForestCover: boolean;
  setShowForestCover: (show: boolean) => void;
  showDeadwood: boolean;
  setShowDeadwood: (show: boolean) => void;
  showDroneImagery: boolean;
  setShowDroneImagery: (show: boolean) => void;
  // Layer availability
  hasForestCover: boolean;
  hasDeadwood: boolean;
  // Opacity (controls forest cover + deadwood layers)
  opacity: number;
  setOpacity: (value: number) => void;
  // Model info
  modelInfo?: {
    name?: string;
    version?: string;
    description?: string;
  };
  // Feedback actions
  onReportClick: () => void;
  onEditForestCover?: () => void;
  onEditDeadwood?: () => void;
  isLoggedIn: boolean;
}

// Basemap options matching DeadtreesMap
const basemapOptions = [
  { value: "streets-v12", label: "Streets" },
  { value: "satellite-streets-v12", label: "Imagery" },
];

const DatasetLayerControlPanel = ({
  mapStyle,
  onMapStyleChange,
  showForestCover,
  setShowForestCover,
  showDeadwood,
  setShowDeadwood,
  showDroneImagery,
  setShowDroneImagery,
  hasForestCover,
  hasDeadwood,
  opacity,
  setOpacity,
  modelInfo,
  onReportClick,
  onEditForestCover,
  onEditDeadwood,
  isLoggedIn,
}: DatasetLayerControlPanelProps) => {
  // Model info tooltip content
  const modelInfoContent = modelInfo ? (
    <div className="max-w-xs">
      <div className="font-medium">{modelInfo.name || "Segmentation Model"}</div>
      {modelInfo.version && <div className="text-xs text-gray-500">Version: {modelInfo.version}</div>}
      {modelInfo.description && <div className="mt-1 text-xs">{modelInfo.description}</div>}
    </div>
  ) : (
    <div className="max-w-xs">
      <div className="font-medium">AI Segmentation</div>
      <div className="mt-1 text-xs">
        Predictions generated by deep learning model trained on drone imagery.
      </div>
    </div>
  );

  return (
    <div 
      className="flex w-52 flex-col rounded-lg bg-white/95 p-3 shadow-lg backdrop-blur-sm"
      onMouseMove={(e) => e.stopPropagation()}
      onMouseEnter={(e) => e.stopPropagation()}
    >
      {/* Basemap Selection */}
      <div className="mb-2 text-xs font-medium text-gray-500">Basemap</div>
      <Segmented
        size="small"
        block
        value={mapStyle}
        onChange={(value) => onMapStyleChange(value as string)}
        options={basemapOptions}
      />

      <Divider className="my-3" />

      {/* Data Layers */}
      <div className="mb-2 flex items-center justify-between">
        <span className="text-xs font-medium text-gray-500">Data Layers</span>
        <Tooltip title={modelInfoContent} placement="left">
          <InfoCircleOutlined className="cursor-help text-gray-400 hover:text-gray-600" />
        </Tooltip>
      </div>
      <div className="flex flex-col gap-1">
        {hasForestCover && (
          <Checkbox 
            checked={showForestCover} 
            onChange={(e) => setShowForestCover(e.target.checked)}
          >
            <span className="flex items-center gap-2">
              <span className="h-3 w-3 rounded-sm bg-green-500" />
              <span className="text-xs text-gray-600">Tree</span>
            </span>
          </Checkbox>
        )}
        {hasDeadwood && (
          <Checkbox 
            checked={showDeadwood} 
            onChange={(e) => setShowDeadwood(e.target.checked)}
          >
            <span className="flex items-center gap-2">
              <span className="h-3 w-3 rounded-sm bg-[#FFB31C]" />
              <span className="text-xs text-gray-600">Standing Deadwood</span>
            </span>
          </Checkbox>
        )}
        <Checkbox 
          checked={showDroneImagery} 
          onChange={(e) => setShowDroneImagery(e.target.checked)}
        >
          <span className="flex items-center gap-2">
            <span className="h-3 w-3 rounded-sm bg-gray-400" />
            <span className="text-xs text-gray-600">Drone Imagery</span>
          </span>
        </Checkbox>
      </div>

      <Divider className="my-3" />

      {/* Opacity - only affects forest cover and deadwood layers */}
      <div className="mb-1 text-xs font-medium text-gray-500">Layer Opacity</div>
      <Slider
        min={0}
        max={1}
        step={0.01}
        value={opacity}
        onChange={setOpacity}
        tooltip={{ formatter: (v) => `${Math.round((v || 0) * 100)}%` }}
        disabled={!showForestCover && !showDeadwood}
      />

      {/* Feedback Section */}
      <div className="-mx-3 -mb-3 mt-3 rounded-b-lg bg-blue-50 px-3 pb-3 pt-2">
        <div className="mb-1 text-xs font-medium text-blue-700">Feedback</div>
        <p className="mb-2 text-xs text-blue-600">
          Help improve predictions by editing or reporting issues
        </p>
        <div className="flex flex-col gap-2">
          {/* Report button - always visible for logged-in users */}
          {isLoggedIn && (
            <Button
              size="small"
              icon={<FlagOutlined />}
              onClick={onReportClick}
              block
            >
              Report Issue
            </Button>
          )}

          {/* Contextual edit buttons - only show when corresponding layer is checked */}
          {isLoggedIn && showForestCover && hasForestCover && onEditForestCover && (
            <Button
              size="small"
              icon={<EditOutlined />}
              onClick={onEditForestCover}
              block
            >
              Edit Forest Cover
            </Button>
          )}

          {isLoggedIn && showDeadwood && hasDeadwood && onEditDeadwood && (
            <Button
              size="small"
              icon={<EditOutlined />}
              onClick={onEditDeadwood}
              block
            >
              Edit Deadwood
            </Button>
          )}

          {/* Prompt for non-logged-in users */}
          {!isLoggedIn && (
            <div className="text-center text-xs text-blue-600">
              <a href="/sign-in" className="text-blue-600 hover:underline">
                Sign in
              </a>
              {" "}to edit predictions
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default DatasetLayerControlPanel;
